### ISSUE TITLE
URTC-SDK怎样集成到支付宝的小程序里

### ISSUE THREAD

**Issue by lucifer0408** [ucloud/urtc-sdk-web#1]
如题，URTC-SDK怎样集成到支付宝的小程序中，直接引用的话报错：
Cannot read property 'navigator' of undefined

**Comment by poplark** [comment]
这个 SDK 是针对 Web 使用的，会通过浏览器  API，window. navigator.mediaDevices.getUserMedia 等相关函数使用摄像头或麦克风设备，支付宝小程序没有全局变量 window，所以不能直接使用，目前我们还没有做针对支付宝小程序的专用的 SDK，后续我们会推出微信小程序的 SDK，支付宝小程序的 SDK 还要看产品计划，敬请关注我们的产品。
