### ISSUE TITLE
web的sdk，Client.muteAudio方法执行时，会终止通话，远端流会被强制退出

### ISSUE THREAD

**Issue by gyfnice** [ucloud/urtc-sdk-web#2]
web的sdk，Client.muteAudio方法执行时，会终止通话，远端流会被强制退出，希望帮忙看看

**Comment by poplark** [comment]
是不是必现的？也麻烦提供下运行环境：
1. 浏览器及版本
2. web sdk 的版本
3. 系统及版本

**Comment by poplark** [comment]
无法复现你碰到的问题
